#include "road_builder.hpp"
#include <fstream>
#include <iostream>
#include <filesystem>

// one entry per surface type
// name = stem used for .obj/.mtl/texture filenames
// tex  = texture filename expected in assets/props
// uv_tile = how many times the texture repeats across the 4m quad
// 1.0 = stretched to fit, 4.0 = 1 repeat per metre (good for most surfaces)
struct RoadDef {
    const char* name;
    const char* tex;
    float uv_tile;
    float w;
    float depth;
    float y_off;
};

static const RoadDef ROAD_TYPES[] = {
    { "asphalt",    "asphalt.jpg",    4.0f, 7.0f, 7.0f, 0.0f    },
    { "gravel",     "gravel.jpg",     4.0f, 7.0f, 7.0f, 0.0f    },
    { "dirt",       "dirt.jpg",       4.0f, 7.0f, 7.0f, 0.0f    },
    { "sand",       "sand.jpg",       3.0f, 7.0f, 7.0f, 0.0f    },
    { "grass",      "grass.jpg",      4.0f, 7.0f, 7.0f, 0.0f    },
    { "cement",     "cement.jpg",     4.0f, 7.0f, 7.0f, 0.0f    },
    { "road_lines", "road_lines.jpg", 1.0f, 7.0f, 0.5f, 0.01f   },
    { "rock"      , "rock.jpg"      , 4.0f, 7.0f, 7.0f, 0.0f    },
};

static const int ROAD_TYPE_COUNT = (int)(sizeof(ROAD_TYPES) / sizeof(ROAD_TYPES[0]));

// writes a flat 4x4m quad OBJ with tiled UVs
// origin at center, y=0, faces up
static void write_road_obj(const std::string& obj_path, const std::string& mtl_name, float uv_tile, float w, float depth, float y_off){
    std::ofstream f(obj_path);
    if (!f.is_open()){
        std::cerr << "[road] failed to write " << obj_path << "\n";
        return;
    }

    f << "mtllib " << mtl_name << ".mtl\n";
    f << "usemtl " << mtl_name << "\n";

    // 4 corners: positions
    float hw = w * 0.5f;
    float hd = depth * 0.5f;
    float u = uv_tile;

    f << "v -" << hw << " " << y_off << "  " << hd << "\n";
    f << "v  " << hw << " " << y_off << "  " << hd << "\n";
    f << "v  " << hw << " " << y_off << " -" << hd << "\n";
    f << "v -" << hw << " " << y_off << " -" << hd << "\n";

    // UVs tiled
    f << "vt 0 0\n";
    f << "vt " << u << " 0\n";
    f << "vt " << u << " " << u << "\n";
    f << "vt 0 " << u << "\n";

    // normal pointing up
    f << "vn 0 1 0\n";

    // two triangles, CCW winding
    f << "f 1/1/1 2/2/1 3/3/1\n";
    f << "f 1/1/1 3/3/1 4/4/1\n";
}

static void write_road_mtl(const std::string& mtl_path, const std::string& mtl_name, const std::string& tex){
    std::ofstream f(mtl_path);
    if (!f.is_open()){
        std::cerr << "[road] failed to write " << mtl_path << "\n";
        return;
    }

    f << "# road material - generated by road_builder\n";
    f << "newmtl " << mtl_name << "\n";
    f << "Kd 1.0 1.0 1.0\n";       // white so texture shows full color
    f << "Ka 0.0 0.0 0.0\n";
    f << "Ks 0.0 0.0 0.0\n";
    f << "map_Kd " << tex << "\n";
}

void road_builder_init(const std::string& assets_dir){
    for (int i = 0; i < ROAD_TYPE_COUNT; i++){
        const RoadDef& r = ROAD_TYPES[i];

        // auto generate flat road texture files in assets_dir= assets/props/
        // dir if texture does not exist already
        std::string obj_path = assets_dir + "/" + r.name + ".obj";
        std::string mtl_path = assets_dir + "/" + r.name + ".mtl";

        // skip if already generated 
        if (std::filesystem::exists(obj_path) && std::filesystem::exists(mtl_path)){
            std::cout << "[road] skipping existing: " << r.name << "\n";
            continue;
        }

        write_road_obj(obj_path, r.name, r.uv_tile, r.w, r.depth, r.y_off);
        write_road_mtl(mtl_path, r.name, r.tex);
        std::cout << "[road] generated: " << r.name << "\n";
    }
}